# Generated by Django 3.0.8 on 2020-07-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='name',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='shor_name'),
        ),
    ]
