# Generated by Django 3.0.8 on 2020-07-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20200730_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
    ]
