# Generated by Django 3.0.8 on 2020-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20200730_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre'),
        ),
    ]
