# Generated by Django 3.0.8 on 2020-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20200730_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='personas.Habilidades'),
        ),
    ]
