# Generated by Django 3.1 on 2020-08-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20200805_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habildiad',
            new_name='habilidad',
        ),
    ]
